name: Setup Environment
description: Setup the Environment for CI
inputs:
  php-version:
    description: The PHP version to install
    default: 8.3
  composer-options:
    description: 'Additional options for composer install'
    default: ''

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        coverage: xdebug

    - name: Install Composer Dependencies
      shell: bash
      run: composer install --prefer-dist --no-progress ${{ inputs.composer-options }}

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: latest
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
